import React, { useState } from 'react';
import { View, Text, ScrollView, Pressable, Platform, StyleSheet } from 'react-native';
import { BlurView } from 'expo-blur';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Animated, {
    useSharedValue,
    useAnimatedStyle,
    useAnimatedScrollHandler,
    interpolate,
    Extrapolation,
} from 'react-native-reanimated';
import { theme, hairlineWidth } from '@/src/theme/colors';
import { ScreenLayout } from '@/src/components/layout/ScreenLayout';
import { CodeBlock } from '@/src/components/ui/CodeBlock';
import { Copy, FileCode, FileJson, Check } from 'lucide-react-native';
import * as Haptics from 'expo-haptics';

const MOCK_FILES = [
    {
        name: 'main.cpp',
        language: 'cpp' as const,
        icon: <FileCode size={14} color="#8b9dc3" />,
        content: `#include <Arduino.h>
#include "pindefs.h"

// Generated by Dedalus AI
// Session ID: 8f3a-2b1c

void setup() {
  Serial.begin(115200);

  // Initialize inputs
  pinMode(PIN_SENSOR_TEMP, INPUT);

  // Initialize outputs
  pinMode(PIN_LED_STATUS, OUTPUT);
  pinMode(PIN_RELAY_MAIN, OUTPUT);

  Serial.println("System Initialized");
}

void loop() {
  // Read Temperature
  int tempRaw = analogRead(PIN_SENSOR_TEMP);
  float voltage = tempRaw * (3.3 / 4095.0);
  float tempC = (voltage - 0.5) * 100;

  // Logic: Active Cooling
  if (tempC > 30.0) {
    digitalWrite(PIN_RELAY_MAIN, HIGH);
    digitalWrite(PIN_LED_STATUS, HIGH);
    Serial.println("Cooling Active");
  } else {
    digitalWrite(PIN_RELAY_MAIN, LOW);

    // Heartbeat pulse
    digitalWrite(PIN_LED_STATUS, (millis() / 1000) % 2);
  }

  delay(100);
}`
    },
    {
        name: 'pindefs.h',
        language: 'cpp' as const,
        icon: <FileCode size={14} color="#8b9dc3" />,
        content: `#ifndef PINDEFS_H
#define PINDEFS_H

// Pin Definitions for ESP32-WROOM
#define PIN_SENSOR_TEMP 34
#define PIN_LED_STATUS  2
#define PIN_RELAY_MAIN  26
#define PIN_I2C_SDA     21
#define PIN_I2C_SCL     22

#endif // PINDEFS_H`
    },
    {
        name: 'platformio.ini',
        language: 'cpp' as const,
        icon: <FileJson size={14} color="#f1fa8c" />,
        content: `[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson @ ^6.19.4
    knolleary/PubSubClient @ ^2.8`
    }
];

export default function CodeScreen() {
    const [selectedFileIndex, setSelectedFileIndex] = useState(0);
    const [copied, setCopied] = useState(false);
    const insets = useSafeAreaInsets();

    const activeFile = MOCK_FILES[selectedFileIndex];

    // Shared value for scroll position
    const scrollY = useSharedValue(0);

    // Scroll handler
    const scrollHandler = useAnimatedScrollHandler((event) => {
        scrollY.value = event.contentOffset.y;
    });

    // Animated style for sticky header
    const stickyHeaderStyle = useAnimatedStyle(() => ({
        opacity: interpolate(scrollY.value, [100, 150], [0, 1], Extrapolation.CLAMP),
        transform: [
            { translateY: interpolate(scrollY.value, [100, 150], [-10, 0], Extrapolation.CLAMP) }
        ],
    }));

    const handleCopy = () => {
        if (Platform.OS === 'ios') {
            Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
        }
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <ScreenLayout useCustomHeader scrollable={false}>
            {/* Animated Sticky Header */}
            <Animated.View
                style={[
                    styles.stickyHeader,
                    { paddingTop: insets.top + theme.layout.headerSafeTopOffset, paddingBottom: 20 },
                    stickyHeaderStyle
                ]}
                pointerEvents="box-none"
            >
                <BlurView
                    intensity={95}
                    tint={theme.blur.material}
                    style={[StyleSheet.absoluteFill, { borderBottomWidth: hairlineWidth, borderBottomColor: theme.border.subtle }]}
                />
                <View style={styles.stickyHeaderContent}>
                    <View style={styles.headerLeft}>
                        <FileCode size={16} color="#ffffff" opacity={0.6} />
                        <Text style={styles.stickyHeaderTitle}>Generated Files</Text>
                    </View>
                    <View style={[styles.statusDot, { width: 6, height: 6, backgroundColor: '#6366f1' }]} />
                </View>
            </Animated.View>

            {/* Scrollable Content */}
            <Animated.ScrollView
                showsVerticalScrollIndicator={true}
                onScroll={scrollHandler}
                scrollEventThrottle={16}
                contentContainerStyle={{
                    paddingTop: insets.top,
                    paddingBottom: 120,
                    paddingHorizontal: theme.layout.padding.screen,
                }}
            >
                {/* Hero Header */}
                <View style={styles.heroHeader}>
                    <BlurView
                        intensity={80}
                        tint={theme.blur.ultraThin}
                        style={StyleSheet.absoluteFill}
                    />
                    <View style={styles.headerContent}>
                        <View style={styles.headerLeft}>
                            <FileCode size={16} color="#ffffff" opacity={0.6} />
                            <View>
                                <Text style={styles.headerSubtitle}>Code</Text>
                                <Text style={styles.headerTitle}>Generated Files</Text>
                            </View>
                        </View>
                        <View style={styles.statusBadge}>
                            <View style={styles.statusDot} />
                            <Text style={styles.headerStatusText}>Ready</Text>
                        </View>
                    </View>
                </View>

                {/* File Tabs */}
                <View style={styles.fileTabs}>
                    <BlurView
                        intensity={60}
                        tint={theme.blur.thin}
                        style={StyleSheet.absoluteFill}
                    />
                    <ScrollView horizontal showsHorizontalScrollIndicator={false}>
                        <View style={styles.tabsRow}>
                            {MOCK_FILES.map((file, idx) => {
                                const isActive = idx === selectedFileIndex;
                                return (
                                    <Pressable
                                        key={file.name}
                                        onPress={() => {
                                            setSelectedFileIndex(idx);
                                            if (Platform.OS === 'ios') {
                                                Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                                            }
                                        }}
                                        style={[
                                            styles.tab,
                                            isActive && styles.tabActive
                                        ]}
                                    >
                                        {React.cloneElement(file.icon as any, {
                                            color: isActive ? '#ffffff' : '#6b7280'
                                        })}
                                        <Text style={[
                                            styles.tabText,
                                            isActive && styles.tabTextActive
                                        ]}>
                                            {file.name}
                                        </Text>
                                    </Pressable>
                                );
                            })}
                        </View>
                    </ScrollView>
                </View>

                {/* Editor Area */}
                <View style={styles.editorContainer}>
                    <BlurView
                        intensity={40}
                        tint={theme.blur.ultraThin}
                        style={StyleSheet.absoluteFill}
                    />
                    <ScrollView
                        style={styles.editorScroll}
                        contentContainerStyle={styles.editorContent}
                        showsVerticalScrollIndicator={true}
                    >
                        <CodeBlock code={activeFile.content} language={activeFile.language} />
                    </ScrollView>

                    {/* Floating Copy Button */}
                    <View style={styles.copyButton}>
                        <Pressable
                            onPress={handleCopy}
                            style={styles.copyButtonInner}
                        >
                            <BlurView
                                intensity={80}
                                tint={theme.blur.material}
                                style={StyleSheet.absoluteFill}
                            />
                            {copied ? (
                                <Check size={22} color="#10b981" strokeWidth={2.5} />
                            ) : (
                                <Copy size={22} color="#ffffff" strokeWidth={2} />
                            )}
                        </Pressable>
                    </View>
                </View>

                {/* Status Bar */}
                <View style={styles.statusBar}>
                    <BlurView
                        intensity={60}
                        tint={theme.blur.thin}
                        style={StyleSheet.absoluteFill}
                    />
                    <View style={styles.statusContent}>
                        <View style={styles.statusLeft}>
                            <Text style={styles.statusText}>Ln 1, Col 1</Text>
                            <Text style={styles.statusText}>UTF-8</Text>
                        </View>
                        <Text style={[styles.statusText, { color: theme.text.secondary }]}>
                            {activeFile.language.toUpperCase()}
                        </Text>
                    </View>
                </View>
            </Animated.ScrollView>
        </ScreenLayout>
    );
}

const styles = StyleSheet.create({
    stickyHeader: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 100,
        paddingHorizontal: theme.layout.padding.screen,
        paddingBottom: 12,
    },
    stickyHeaderContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 4,
    },
    stickyHeaderTitle: {
        fontSize: 17,
        fontWeight: '600',
        color: '#ffffff',
        marginLeft: 8,
    },
    heroHeader: {
        marginBottom: 16,
        borderRadius: theme.layout.borderRadius.lg,
        borderWidth: hairlineWidth,
        borderColor: theme.border.default,
        overflow: 'hidden',
    },
    headerContent: {
        paddingHorizontal: 20,
        paddingVertical: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    headerSubtitle: {
        fontSize: 10,
        color: 'rgba(255, 255, 255, 0.6)',
        fontFamily: 'monospace',
        textTransform: 'uppercase',
        letterSpacing: 1.5,
    },
    headerTitle: {
        fontSize: 20,
        color: '#ffffff',
        fontWeight: '600',
        letterSpacing: -0.5,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#6366f1',
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
    },
    headerStatusText: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.7)',
        fontFamily: 'monospace',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    fileTabs: {
        marginBottom: 16,
        borderRadius: theme.layout.borderRadius.lg,
        borderWidth: hairlineWidth,
        borderColor: theme.border.default,
        overflow: 'hidden',
    },
    tabsRow: {
        flexDirection: 'row',
        paddingHorizontal: 8,
        paddingVertical: 8,
    },
    tab: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 16,
        paddingVertical: 8,
        marginRight: 8,
        borderRadius: theme.layout.borderRadius.md,
    },
    tabActive: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
    },
    tabText: {
        fontFamily: 'monospace',
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.5)',
    },
    tabTextActive: {
        color: '#ffffff',
        fontWeight: '600',
    },
    editorContainer: {
        flex: 1,
        borderRadius: theme.layout.borderRadius.lg,
        borderWidth: hairlineWidth,
        borderColor: theme.border.default,
        overflow: 'hidden',
        marginBottom: 16,
    },
    editorScroll: {
        flex: 1,
    },
    editorContent: {
        padding: 16,
    },
    copyButton: {
        position: 'absolute',
        bottom: 24,
        right: 24,
    },
    copyButtonInner: {
        borderRadius: 999,
        borderWidth: hairlineWidth,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        overflow: 'hidden',
        padding: 16,
    },
    statusBar: {
        borderRadius: theme.layout.borderRadius.lg,
        borderWidth: hairlineWidth,
        borderColor: theme.border.default,
        overflow: 'hidden',
    },
    statusContent: {
        paddingHorizontal: 20,
        paddingVertical: 12,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    statusLeft: {
        flexDirection: 'row',
        gap: 16,
    },
    statusText: {
        fontSize: 10,
        fontFamily: 'monospace',
        color: 'rgba(255, 255, 255, 0.5)',
    },
});
